### ISSUE TITLE
Breaks on example from readme

### ISSUE THREAD

**Issue by keddad** [fabiommendes/ejudge#1]
Trying to test it, after installing with pip, faced with an issue:
```
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
>>> from ejudge import run
>>> src = 'print("hello %s!" % input("name: "))'
>>> inputs = ['john']
>>> spec = run(src, inputs, lang='python')

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/keddad/PycharmProjects/helloworld/venv/lib/python3.6/site-packages/ejudge/functions.py", line 58, in run
    return run_worker(**locals())[0]
  File "/home/keddad/PycharmProjects/helloworld/venv/lib/python3.6/site-packages/ejudge/functions.py", line 112, in run_worker
    print_messages=True,
  File "/home/keddad/PycharmProjects/helloworld/venv/lib/python3.6/site-packages/boxed/jsonbox/__init__.py", line 43, in run
    target=target,
  File "/home/keddad/PycharmProjects/helloworld/venv/lib/python3.6/site-packages/boxed/core.py", line 636, in execute_subprocess
    env={'PYTHONPATH': pythonpath()})
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python_boxed': 'python_boxed'

```
If there are any way to fix this problem?

**Comment by NekitPnt** [comment]
Have you solved this problem? I came across exactly the same one

**Comment by keddad** [comment]
> Have you solved this problem? I came across exactly the same one

Nope :(
